### ISSUE TITLE
Notes on Part 4: Field of View.

### ISSUE THREAD

**Issue by HexDecimal** [TStand90/tcod_tutorial_v2#14]
The modern API does FOV with [tcod.map.compute_fov](https://python-tcod.readthedocs.io/en/latest/tcod/map.html#tcod.map.compute_fov).  The syntax will be familiar, you just need to add in the transparency array.

The `visible`/`explored` arrays should be added as separate arrays, not added in the tile dtype.

A `memory` array could be added with a graphics dtype and filled with a blank shroud graphic.  This array would hold the dark graphics and be used for non-visible areas of the map.  You could also put item and enemy graphics here so that they show as ghosts when out of view.  The `memory` array can hold out of date data so that changes to the `tiles` array are not reflected until the player sees the changes themselves.

[np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where) will be used a lot here.  Think of it like a ternary operator. `out = (cond ? a : b)` is similar to `out = np.where(cond, a, b)` but `np.where` works on entire arrays.

**Comment by TStand90** [comment]
I think the "memory" idea is great, though it might be best left as an extra. Whether the player should see entities no longer in the FOV feels like a design decision that the person following the tutorial should evaluate and make themselves, though it does make sense to show items out of range, I think.

I'm experimenting with how to do this, and here's what I ended up with for the `GameMap.render` method:

```
    def render(self, console: Console) -> None:
        console.tiles_rgb[0:self.width, 0:self.height] = np.where(
            self.visible,
            self.tiles["light"],
            np.where(self.explored, self.tiles["dark"], self.tiles["empty"])
        )
```

This works, but is there a better way to tell console.tiles_rgb to not draw anything than creating a new "empty" graphic data type in all the tiles?

Here's what I did for that:

```
tile_dt = np.dtype(
    [
        ("walkable", np.bool),  # True if this tile can be walked over.
        ("transparent", np.bool),  # True if this tile doesn't block FOV.
        ("dark", graphic_dt),  # Graphics for when this tile is not in FOV.
        ("light", graphic_dt), # Graphics for when this tile is in FOV.
        ("empty", graphic_dt)
    ]
)


def new_tile(
    *,  # Enforce the use of keywords, so that parameter order doesn't matter.
    walkable: int,
    transparent: int,
    dark: Tuple[int, Tuple[int, int, int], Tuple[int, int, int]],
    light: Tuple[int, Tuple[int, int, int], Tuple[int, int, int]],
) -> np.ndarray:
    """Helper function for defining individual tile types """
    return np.array((walkable, transparent, dark, light, (ord(" "), (0, 0, 0), (0, 0, 0))), dtype=tile_dt)


floor = new_tile(
    walkable=True,
    transparent=True,
    dark=(ord(" "), (255, 255, 255), (50, 50, 150)),
    light=(ord(" "), (255, 255, 255), (200, 180, 50))
)
wall = new_tile(
    walkable=False,
    transparent=False,
    dark=(ord(" "), (255, 255, 255), (0, 0, 100)),
    light=(ord(" "), (255, 255, 255), (130, 110, 50)),
)
```

I feel like I'm missing something obvious with the "empty" part.

**Comment by HexDecimal** [comment]
> I think the "memory" idea is great, though it might be best left as an extra.

That's fine.  I really need you to tell me 'no' whenever I present anything too over engineered, because I usually don't realize it.

> This works, but is there a better way to tell console.tiles_rgb to not draw anything than creating a new "empty" graphic data type in all the tiles?

An array with 1 element can be used as a NumPy scalar which can broadcast to the entire array.  So you only need a scalar to represent all the darkness/shroud/empty:
```python
SHROUD = np.array((0x20, (255, 255, 255), (0, 0, 0)), dtype=graphic_dt)
```

> I'm experimenting with how to do this, and here's what I ended up with for the GameMap.render method

You almost recreated [the rendering that I typically use](https://github.com/HexDecimal/roguelike-tutorial/blob/805b6583f42cf2b6c4409141437bbce78d2a1747/gamemap.py#L135-L140).  You'll want [np.select](https://numpy.org/doc/stable/reference/generated/numpy.select.html#numpy.select) to get the `if..elif..else` behavior from chaining together `np.where`'s, then you add the above scalar.

```python
console.tiles_rgb[0:self.width, 0:self.height] = np.select(
    condlist=[self.visible, self.explored],
    choicelist=[self.tiles["light"], self.tiles["dark"]],
    default=SHROUD,
)
```

**Comment by TStand90** [comment]
I've implemented your SHROUD and np.select suggestions in the part-4 branch.
