### ISSUE TITLE
Part 5: Context sensitive actions.

### ISSUE THREAD

**Issue by HexDecimal** [TStand90/tcod_tutorial_v2#16]
In part 5, what happens when the player picks a direction becomes context sensitive, and I think that the actions should reflect this.

The current movement could be changed into generic "bump" action.  This action selects another action to perform based on the context (move onto tile, attack entity, open door.)  Since multiple actions will have `dx` and `dy` it might be a good idea to build a hierarchy of actions, for example:
```python
class ActionWithDirection(Action):
    """An action with relative direction parameters."""

    def __init__(self, dx: int, dy: int):
        super().__init__()
        self.dx = dx
        self.dy = dy

class BumpAction(ActionWithDirection):
    """Perform a context sensitive action based on a direction."""

    def perform(self, engine: Engine, entity: Entity) -> None:
        if ...:  # Enemy fighter is here.
            return MeleeAction(self.dx, self.dy).perform(engine, entity)

        # Default case, try to move onto the tile.
        return MovementAction(self.dx, self.dy).perform(engine, entity)
```

**Comment by TStand90** [comment]
Makes sense to me. I imagine this pattern will also come in handy in later parts, like when ranged targeting comes up.

**Comment by HexDecimal** [comment]
Ranged targeting might be tricky.  It would invoke handling events for an unresolved action so an event handler would need to be involved.  That will likely come up during inventory management in part 8.

**Comment by HexDecimal** [comment]
A pattern where actions invoke each other is better for AI, and will be needed in part 6.

**Comment by TStand90** [comment]
Closing this issue for now, as the suggestion was implemented.
