### ISSUE TITLE
Part 5: Entity contianer issues.

### ISSUE THREAD

**Issue by HexDecimal** [TStand90/tcod_tutorial_v2#17]
Currently entities are stored in `Engine.entities`, but it might be better move this container to the `GameMap` class instead.

Until then the `procgen.generate_dungeon` function doesn't have enough scope to spawn new entities.  This change would also make it easier to keep persistent maps, and you won't have to clear it manually when moving to a new level (part 11.)

I'd make a PR but I'm not sure where and when to make it right now. I have changes to part 2 here: https://github.com/TStand90/tcod_tutorial_v2/compare/part-2...HexDecimal:entities-in-map, but this would be easy to do in part 5.

**Comment by TStand90** [comment]
I agree with this idea. Persistent maps was an "extra" idea I had, so doing this now will make that much easier. Pretty much every time I've tried "expanding" the tutorial into a real roguelike game, one of the first things I do is move the "entities" into the map.

It's probably okay to have the tutorial move "entities" from `Engine` to `GameMap` in part 5. I think for part 2, it made sense to keep `entities` in `Engine`, but now it makes sense to keep it in `GameMap`. It shouldn't be a huge change, I think.

**Comment by TStand90** [comment]
Closing this issue, "entities" are now part of the game map.
