### ISSUE TITLE
Question regarding best practices

### ISSUE THREAD

**Issue by bmanturner** [TStand90/tcod_tutorial_v2#40]
Hey all. Thank you so much for the enlightening tutorial.

This snippet got me thinking:

```python
class Fighter(BaseComponent):
    entity: Actor
```

As the `Fighter` class uses properties of `Actor` that do not exist in `Entity`, would it be more proper to name this property `actor` instead?

I know this type of feedback can come across as criticism, but I genuinely do not know as I am a novice when it comes to python (outside of data processing).

**Comment by HexDecimal** [comment]
It inherits from `BaseComponent` which I assume has `entity: Entity`.  The line `entity: Actor` is used to narrow which type is expected in that slot for `Fighter` while staying compatible with other `BaseComponent` methods.

This wasn't my best work and there could be some other issues which come from doing things like this, but MyPy considered this valid when it was written and probably still does.

**Comment by bmanturner** [comment]
Ah. “Narrowing” the acceptable type for the SubClass jives with me. That seems right now. Thanks!
