### ISSUE TITLE
Question: Difference between going to engine vs entity for game_map?

### ISSUE THREAD

**Issue by bmanturner** [TStand90/tcod_tutorial_v2#41]
I notice most of the time we go to engine for game_map, even though it's accessible via entity. Would you mind taking a moment to explain the difference in thought behind when you might access it via one or the other?

Thank you

**Comment by HexDecimal** [comment]
`Action` is missing a `game_map` property.  You can add one which will shorten the code.  Until then it's either `self.engine.game_map` or `self.entity.game_map` to get the `GameMap`.  The latter is probably better in the long term.  The former assumes that actions will only happen in the active `GameMap`.

**Comment by bmanturner** [comment]
This code is well-organized but that distinction has always tripped me up so I’m likely to rename `engine.game_map` to `engine.active_game_map` in my repo.
