### ISSUE TITLE
Notes on tcod event handling.

### ISSUE THREAD

**Issue by HexDecimal** [TStand90/tcod_tutorial_v2#5]
By default variables returned by `tcod.event` are not typed:
```python
for event in tcod.event.wait():
    ...  # event is type Any
    if event.type == "KEYDOWN":
        ...  # event is type Any, there is no static type checking for it in this block.
```
Something which can be done is to use `isinstance` to differentiate them.  I used to avoid this function a lot since it had potential to mess up Python's duck-typing, but things have improved since then and now I just avoid it because I'm old:
```python
for event in tcod.event.wait():
    ...  # event is type Any
    if isinstance(event, tcod.event.KeyDown):
        ...  # event is type KeyDown
```
Another option is [tcod.event.EventDispatch](https://python-tcod.readthedocs.io/en/latest/tcod/event.html#tcod.event.EventDispatch), this class passes events to overridable methods based on their type, the class can also return a hinted type from those functions:
```python
class EventHandler(tcod.event.EventDispatch[Action]):
    def ev_keydown(event: tcod.event.KeyDown) -> Optional[Action]:
        ... # event is type KeyDown


handler = EventHandler()
for event in tcod.event.wait():
    ...  # event is type Any
    action = handler.dispatch(event)
    ...  # action is type Optional[Action]
    if not action:
        continue
    ... # action is type Action
```
`EventDispatch` is nice since it can be subclassed into an abstract state class which can then be subclassed into a set of states.  The last tutorial already used states but didn't use the double dispatch pattern.  You can look at [my implementation of states](https://github.com/HexDecimal/roguelike-tutorial/tree/master/states) to see a likely over engineered example.

**Comment by TStand90** [comment]
I think the "isinstance" syntax works well. I tried the EventDispatch method as well, which seems pretty intuitive. It might require some handwaving for this early in the tutorial, since it might be a bit much for a beginner to grasp.

**Comment by TStand90** [comment]
@HexDecimal Take a look at branch event-handler and see if I'm on the right track here.

https://github.com/TStand90/tcod_tutorial_v2/tree/event-handler

**Comment by HexDecimal** [comment]
I mostly just put out these thoughts as things to consider.  I can't actually be trusted with design.

Since the reason to use `EventDispatch` sub-classes would be to replace the GameStates enum.  The class names and variables should reflect that.  With a name like `PlayerState`, `PlayerTurn`, or `IngameState`, and the variable could be `state` instead of `event_handler`.  The class would be given a new method for drawing on the screen, so that different states could render different things and menus, and `event_handler/state` would be swapped out depending on the games state.  What that should do is make it easier to create new states no matter the purpose.

`ev_quit` is missing a return annotation, which can either be `Optional[Action]` or `None`.  `Optional[Action]` can't be used in a sub-class if `None` was used in the parent.
