### ISSUE TITLE
Part 6: AttributeError: 'Actor' object has no attribute 'render_order'

### ISSUE THREAD

**Issue by mvittorazzi** [TStand90/tcod_tutorial_v2#52]
Hello!

I'm getting the following error when trying to run the project after finishing part 6:

![image](https://user-images.githubusercontent.com/3996173/145657161-ee969cea-1812-4aca-82d1-1824b68171ec.png)

Here's the lambda part in game_map:

![image](https://user-images.githubusercontent.com/3996173/145657189-a9a208c3-f93e-4de9-9ce0-6ee579c1e11b.png)

I've double-checked it all from the start and couldn't figure out what is the problem, even comparing the files from the repository version (Which in contrast is running fine).

I'm running Python 3.9.0 and not using a virtual environment.

**Comment by Vaiterius** [comment]
Hmm, my game runs fine and I've never gotten that error. Try checking to see if your Entity class actually contains the render_order attribute? The Actor class should also have inherited the render_order attribute. Or a misspelling maybe?

**Comment by mvittorazzi** [comment]
> Hmm, my game runs fine and I've never gotten that error. Try checking to see if your Entity class actually contains the render_order attribute? The Actor class should also have inherited the render_order attribute. Or a misspelling maybe?

Yup, it was indeed a mistyping! I've been studying Python for only a week and working the whole day on this sole part, my eyes were already playing tricks!

Thanks, @Vaiterius.
