### ISSUE TITLE
Entities is initialized as a list, but code treats it as a set.

### ISSUE THREAD

**Issue by Dowsley** [TStand90/tcod_tutorial_v2#57]
https://github.com/TStand90/tcod_tutorial_v2/blob/6e763f14a5a0345b6f3620c3ff3bd989145b5ac7/procgen.py#L92

Python 3.10 will break with other parts of the code such as.

```
for entity in self.game_map.entities - {self.player}:
TypeError: unsupported operand type(s) for -: 'list' and 'set'
```

It seems to be a simple fix - just declare it as `{player}`. I didn't make a pull request because I don't know in which part this "mistake" began, or if there's something else I'm missing.

**Comment by HexDecimal** [comment]
`GameMap`'s initializer always converts that input into a `set`, this part is missing from your code:

https://github.com/TStand90/tcod_tutorial_v2/blob/6e763f14a5a0345b6f3620c3ff3bd989145b5ac7/game_map.py#L14-L17

Your change would be a little more efficient though. Some classes would probably be better written with `attrs`.

**Comment by Dowsley** [comment]
Thank you, I missed that default when following your guide.

I believe it's not worth a change given that.
